//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmarks
    {
        public int BookmarkID { get; set; }
        public int Collection_BookID { get; set; }
        public int Page { get; set; }
    
        public virtual Collection_Book Collection_Book { get; set; }
    }
}
